appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a63aeb3c070044c69e
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: 13kuPsZ4uPVWbfwzy7hs5y5QckKWKYECa6nTSs2BoBYoSL9QS2Fa9w+pGAOOcCjKQT01t45tq0FRRyB6yaMYvYlWDLnjen3QjkKoTV6Ty5+DB8OF5TcHOZYTKTUA3ps1V4KPViOwuhxk5ChiCgJsugzGOU5bKuIcMWvBU8FaXIxARdRbaF4tnTwF06X8KOCtZwuQRGUOdjhAS0hnm4oXA6hqdsZHBnJY5eS6DsdYQAWD7eM2OCJyIj4ROC0f+coHny+JOb33/0wecT3M+0z/4pWN8BRWcv49EQuSLdSSMCJVyX/cLpwU71o5o+caSiHRAhIi0ieCqI3+Tq3ye4/bG8zgtrObJ/mklpe/ihwyzKp9Vc3Ex7MiOjSkWPQUdtTQNAWqzFJZtQaZBFR5YkhWVDgq2z+mI1tGgG+HRznJxxbY9pPZtdhOj+Rf53uQsLQE3pACNpnnetcMz3ZI8nXse61IQKNsQGIsu0v93hDNmasRxs6ONA5oIjXYzobUjdk92u5dzQPU7ilF7YC1wcnFQUlsC+YYCcI588bTkN6VANgUiMF2bVUevuRynQH98NDgp+LxhOEjDdfa7ujg5WTQ9Unpfi4/6SzufIvaxCdvmt2MV79qw57C4DzzmiiOt2Z7lEMpXawLK7W23psAOXf2DGa0v9JZNKpEjqcrmhQ9RP4=}
